apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: cf-ex-php-info
  namespace: dev-ns-03
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/auto-configure-actuators: "true"
    app.kubernetes.io/part-of: cf-ex-php-info
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/JanKraut/cf-ex-php-info
      ref:
        branch: master
